### ISSUE TITLE
Any check-point whether HAT is working from H/W ?

### ISSUE THREAD

**Issue by vkcorp** [Xinyuan-LilyGO/T-SimHat#2]
I have some issue and checking the problem.
I think it's software problem but how I can sure it...
So I wonder :
Is there any LED/blinking or else for checking my HAT is working or not (part of H/W level) ?

**Comment by LilyGO** [comment]
Hello，The control relay switch LED light will also go on and off

**Comment by vkcorp** [comment]
Could you show me where it is on board ? I found nothing blinked in my HAT.
Or do I have to use additional API to make it blinked ?

**Comment by LilyGO** [comment]
Refer to the [sketch](https://github.com/Xinyuan-LilyGO/T-SimHat/blob/main/examples/simple/simple.ino)

**Comment by vkcorp** [comment]
Which point can be refered to use for checking H/W functionality ?

**Comment by vkcorp** [comment]
Maybe these lines are for checking the status of Relay with blinking LED on HAT,

> 

    static uint32_t Millis;
    if (millis() - Millis > 1000) {
        digitalWrite(RELAY_PIN, !digitalRead(RELAY_PIN));
        Millis = millis();
    }
